"""Markdown rendering for the HTTP API layer and ``llms.txt``.

Like upstream Markdownizer, rendering is verbatim and structural: it never
invents documentation. The route section reports what the live application
exposes.
"""

from __future__ import annotations

from markdownizer_fastapi.enrich import EnrichedProject
from markdownizer_fastapi.routes import RouteInfo

_SUMMARY_LIMIT = 200


def _clean(text: str) -> str:
    return " ".join(text.replace("`", "'").split())[:_SUMMARY_LIMIT]


def _route_heading(route: RouteInfo) -> str:
    methods = ", ".join(route.methods) if route.methods else "ANY"
    return f"### `{methods} {route.path}`"


def render_routes_markdown(routes: list[RouteInfo]) -> str:
    """Render the matched route table as a deterministic Markdown section."""
    lines: list[str] = ["## HTTP API", ""]
    matched = [route for route in routes if route.matched]
    unmatched = [route for route in routes if not route.matched]

    for route in matched:
        lines.append(_route_heading(route))
        lines.append("")
        if route.symbol_id:
            lines.append(f"- Handler: `{route.symbol_id}`")
        if route.summary:
            lines.append(f"- Summary: {_clean(route.summary)}")
        if route.tags:
            lines.append(f"- Tags: {', '.join(f'`{tag}`' for tag in route.tags)}")
        if route.response_model:
            lines.append(f"- Response model: `{route.response_model}`")
        if route.dependencies:
            rendered = ", ".join(f"`{name}`" for name in route.dependencies)
            lines.append(f"- Dependencies: {rendered}")
        if route.status_code is not None:
            lines.append(f"- Status code: {route.status_code}")
        if route.deprecated:
            lines.append("- Deprecated")
        lines.append("")

    if unmatched:
        lines.append("### Runtime-only routes")
        lines.append("")
        for route in unmatched:
            reason = route.unmatched_reason or "not_in_ir"
            methods = ", ".join(route.methods) if route.methods else "ANY"
            summary = f" — {_clean(route.summary)}" if route.summary else ""
            lines.append(f"- `{methods} {route.path}` ({reason}){summary}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_llms_txt(project: EnrichedProject, prefix: str) -> str:
    """Render an ``llms.txt`` index. The index never contains source code."""
    ir = project.ir
    lines: list[str] = [
        f"# {ir.name}",
        "",
        (
            f"> Deterministic Markdown index generated by Markdownizer "
            f"(IR v{ir.ir_version}, hash {ir.hash}; {ir.stats.module_count} modules, "
            f"{ir.stats.symbol_count} symbols, {len(project.routes)} HTTP routes)."
        ),
        "",
        "## Context",
        "",
        f"- [context.md]({prefix}/context.md): ranked, token-budgeted context",
        f"- [project.json]({prefix}/project.json): full Project IR",
        f"- [routes.json]({prefix}/routes.json): live HTTP route table",
        f"- [stats]({prefix}/stats): project statistics",
        "",
        "## Packages",
        "",
    ]
    for package in sorted(ir.packages, key=lambda package: package.name):
        lines.append(f"- `{package.name}`")
    lines.append("")

    if project.routes:
        lines.append("## HTTP API")
        lines.append("")
        for route in project.routes:
            methods = ", ".join(route.methods) if route.methods else "ANY"
            summary = f" — {_clean(route.summary)}" if route.summary else ""
            lines.append(f"- `{methods} {route.path}`{summary}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
